      - name: Run Equity Scraper
        run: python scraper.py

      - name: Split F&O Equity Stocks into Individual CSVs
        run: python split_fo_equity_stocks.py

      - name: Save Data to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stocks/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update F&O Equity Stock Files [skip ci]" && git push)
